### ISSUE TITLE
Updated parts list for v1.2

### ISSUE THREAD

**Issue by neerolyte** [vhs/vhs-pcbs#5]
Hi, the [Tindie page](https://www.tindie.com/products/TomKeddie/usb-isolator-pcb-only/) mentions that the documentation here should have been updated here for v1.2, however the LEDs and associated resistors are missing from the parts list.

I'm very new at this so wondering if you could at least confirm that these look ok and preferably also update the parts list.

I'm looking at a pretty small LED as the pads seem pretty close together, this one is 1.6mm end-to-end so should comfortably fit with room to solder:
http://www.farnell.com/datasheets/1776846.pdf

For the resistor I think any 0805 package should be ok?

To get the 20mA I believe ideally I'd have a 145 ohm resistor (`(Vs - Vd)/Id = (5-2.1)/0.02 = 145`) - 150 ohm seems to be a very common size, so I think I can just use that as it's "close enough"?
 
Cheers,
Dave

**Comment by TomKeddie** [comment]
Hi Dave,

Perhaps the PDF is out of date but the README.md has the LEDs in the list.

https://github.com/TomKeddie/vhs-pcbs/tree/master/usb-isolator

The LEDs are 0805 but it is always easier hand solder a size smaller if you want.  0805 or 0603 will work fine.

I used 1k, you don't need 20mA to turn the led on, just a few mA is enough.

KP-2012EC looks like the cheapest 0805 on Farnell, LGQ971 if you want 0603.

Sorry for any confusion,
Cheers,
Tom

**Comment by neerolyte** [comment]
Oh thanks for the quick reply!

The Tindie page links to a clone of the repo, which seems to be behind your other one: https://github.com/vhs/vhs-pcbs/tree/master/usb-isolator (hence the confusion).

I should have given the exact link for what I was looking at, sorry.

Cheers,
Dave

**Comment by TomKeddie** [comment]
Cheers.
